# Generated by Django 4.2 on 2023-05-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('visto', models.BooleanField(default=False)),
            ],
        ),
    ]
