# Generated by Django 4.2 on 2023-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='imagen',
            field=models.TextField(),
        ),
    ]
